export const notifications: AppNotification[] = [
  {
    id: 1,
    type: 'message',
    sender: 'Alice Johnson',
    avatar: '',
    initials: 'AJ',
    preview: 'Halo, bisa bantu aku review PR?',
    time: '10:30',
    read: false,
  },
  {
    id: 2,
    type: 'system',
    title: 'Maintenance Scheduled',
    description: 'Server akan maintenance pada 15 April 2026 pukul 02:00 WIB.',
    time: '09:00',
    read: false,
  },
  {
    id: 3,
    type: 'invite',
    sender: 'Bob Smith',
    avatar: '',
    initials: 'BS',
    groupName: 'Frontend Team',
    time: 'Kemarin',
    read: true,
  },
  {
    id: 4,
    type: 'system',
    title: 'Update Available',
    description: 'Versi baru aplikasi tersedia. Silakan update ke v2.1.0.',
    time: 'Kemarin',
    read: true,
  },
  {
    id: 5,
    type: 'message',
    sender: 'Charlie Brown',
    avatar: '',
    initials: 'CB',
    preview: 'Deploy sudah selesai, cek staging ya',
    time: 'Senin',
    read: true,
  },
  {
    id: 6,
    type: 'invite',
    sender: 'Diana Ross',
    avatar: '',
    initials: 'DR',
    groupName: 'Project Alpha',
    time: 'Senin',
    read: false,
  },
];
